// @create-index

export { default as template } from "./template.js";
export { default as user } from "./user.js";
export { default as auth } from "./auth.js";
export { default as category } from "./category.js";
export { default as part } from "./part.js";
export { default as dialog } from "./dialog.js";
// export { default as book } from "./book.js";
// export { default as catalog } from "./catalog.js";
// export { default as comment } from "./comment.js";
// export { default as config } from "./config.js";
// export { default as faq } from "./faq.js";
// export { default as file } from "./file.js";
// export { default as guide } from "./guide.js";
// export { default as map } from "./map.js";
// export { default as menu } from "./menu.js";
// export { default as offCode } from "./offCode.js";
// export { default as otp } from "./otp.js";
// export { default as process } from "./process.js";
// export { default as product } from "./product.js";
// export { default as publicApi } from "./publicApi.js";
// export { default as report } from "./report.js";
// export { default as role } from "./role.js";
// export { default as roleFunction } from "./roleFunction.js";
// export { default as userFactor } from "./userFactor.js";
// export { default as userFavorite } from "./userFavorite.js";
// export { default as userProduct } from "./userProduct.js";
// export { default as userAddress } from "./userAddress.js";
// export { default as admin } from "./admin.js";
// export { default as craft } from "./craft.js";
// export { default as transport } from "./transport.js";
